/*
    Masala
    Copyright (C) 2022 Vikram K. Mulligan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/// @file src/core_api/base_classes/selectors/atom_selectors/AtomSelection.cc
/// @brief A pure virtual base class for AtomSelections.
/// @details AtomSelections are generated by AtomSelectors, and provide a list of a
/// subset of atoms to select.  They are dependent on the current Pose.
/// @note Since this class does not implement class_name() or class_namespace()
/// functions required by the MasalaObject base class, it remains pure virtual.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).

// Unit header:
#include <core_api/base_classes/selectors/atom_selectors/AtomSelection.hh>

// STL headers:
#include <string>

namespace masala {
namespace core_api {
namespace base_classes {
namespace selectors {
namespace atom_selectors {

////////////////////////////////////////////////////////////////////////////////
// PUBLIC MEMBER FUNCTIONS
////////////////////////////////////////////////////////////////////////////////

/// @brief Get the name of this class ("AtomSelection").
std::string
AtomSelection::class_name() const {
	return "AtomSelection";
}

/// @brief Get the namespace of this class ("masala::core_api::base_classes::selectors::atom_selectors").
std::string
AtomSelection::class_namespace() const {
	return "masala::core_api::base_classes::selectors::atom_selectors";
}

/// @brief Get the category or categories for this plugin class.
/// @returns { { "Selection", "AtomSelection" } }
/// @note Categories are hierarchical (e.g. Selector->AtomSelector->AnnotatedRegionSelector,
/// stored as { {"Selector", "AtomSelector", "AnnotatedRegionSelector"} }). A plugin can be
/// in more than one hierarchical category (in which case there would be more than one
/// entry in the outher vector), but must be in at least one.  The first one is used as
/// the primary key.
std::vector< std::vector< std::string > >
AtomSelection::get_categories() const {
	return std::vector< std::vector< std::string > > {
		{ "Selection", "AtomSelection" }
	};
}

/// @brief Get the keywords for this plugin class.
/// @returns { "masala", "core", "selection", "atom_selection" }
std::vector< std::string >
AtomSelection::get_keywords() const {
	return std::vector< std::string > {
		"masala",
		"core",
		"selection",
		"atom_selection"
	};
}

/// @brief Ensure that an atom selection has enough memory allocated so that it
/// can store at least N atoms.
/// @details Calls STL vector reserve() function, which suggests memory allocation.
void
AtomSelection::reserve(
	core_api::Size const n_atoms
) {
	atoms_.reserve(n_atoms);
}

/// @brief Suggest deallocation of unused storage capacity.
/// @details Calls STL vector shrink_to_fit() function, which suggests memory deallocation.
void
AtomSelection::shrink_to_fit() {
	atoms_.shrink_to_fit();
}

/// @brief Add an atom to the selection
void
AtomSelection::add_atom(
	core_api::auto_generated_api::chemistry::atoms::AtomInstance_APICSP const & atom_in
) {
	// Do not add if already in vector.
	for( auto const & entry : atoms_ ) {
		if( entry.lock() == atom_in ) {
			return;
		}
	}
	atoms_.push_back( atom_in );
}

/// @brief Get the number of selected atoms in this selection.
core_api::Size
AtomSelection::num_selected_atoms() const {
	return atoms_.size();
}

/// @brief An iterator pointing to the first atom.
std::vector< masala::core_api::auto_generated_api::chemistry::atoms::AtomInstance_APICWP >::const_iterator
AtomSelection::atoms_begin() const {
	return atoms_.begin();
}

/// @brief An iterator pointing to the element past the last atom.
std::vector< masala::core_api::auto_generated_api::chemistry::atoms::AtomInstance_APICWP >::const_iterator
AtomSelection::atoms_end() const {
	return atoms_.end();
}

} // namespace atom_selectors
} // namespace selectors
} // namespace base_classes
} // namespace core_api
} // namespace masala
