/*
MIT License

Copyright (c) 2022 Vikram K. Mulligan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/// @file src/core_api/base_classes/selectors/atom_selectors/AtomSelection.fwd.hh
/// @brief Header for a pure virtual base class for AtomSelections.
/// @details AtomSelections are generated by AtomSelectors, and provide a list of a
/// subset of atoms to select.  They are dependent on the current Pose.
/// @note Since this class does not implement class_name() or class_namespace()
/// functions required by the MasalaObject base class, it remains pure virtual.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).

#ifndef Masala_src_core_api_base_classes_selectors_atom_selectors_AtomSelection_hh
#define Masala_src_core_api_base_classes_selectors_atom_selectors_AtomSelection_hh

// Parent class:
#include <core_api/base_classes/selectors/Selection.hh>

// Forward declarations:
#include <core_api/base_classes/selectors/atom_selectors/AtomSelection.fwd.hh>
#include <core_api/auto_generated_api/chemistry/atoms/AtomInstance_API.fwd.hh>

// Core headers:
#include <core_api/types.hh>

// Base headers:
#include <base/MasalaObject.hh>

// STL headers:
#include <vector>

namespace masala {
namespace core_api {
namespace base_classes {
namespace selectors {
namespace atom_selectors {

/// @brief A pure virtual base class for AtomSelections.
/// @details AtomSelections are generated by AtomSelectors, and provide a list of a
/// subset of atoms to select.  They are dependent on the current Pose.
/// @note Since this class does not implement class_name() or class_namespace()
/// functions required by the MasalaObject base class, it remains pure virtual.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).
class AtomSelection : public core_api::base_classes::selectors::Selection {

public:

	/// @brief Default constructor.
	AtomSelection() = default;

	/// @brief Copy constructor.
	AtomSelection( AtomSelection const & ) = default;

	/// @brief Destructor.
	~AtomSelection() override = default;

public:

////////////////////////////////////////////////////////////////////////////////
// PUBLIC MEMBER FUNCTIONS
////////////////////////////////////////////////////////////////////////////////

	/// @brief Get the name of this class ("AtomSelection").
	std::string class_name() const override;

	/// @brief Get the namespace of this class ("masala::core_api::base_classes::selectors::atom_selectors").
	std::string class_namespace() const override;

	/// @brief Ensure that an atom selection has enough memory allocated so that it
	/// can store at least N atoms.
	/// @details Calls STL vector reserve() function, which suggests memory allocation.
	void reserve( core_api::Size const n_atoms );

	/// @brief Suggest deallocation of unused storage capacity.
	/// @details Calls STL vector shrink_to_fit() function, which suggests memory deallocation.
	void shrink_to_fit();

	/// @brief Add an atom to the selection
	void add_atom( core_api::auto_generated_api::chemistry::atoms::AtomInstance_APICSP const & atom_in );

private:

////////////////////////////////////////////////////////////////////////////////
// PRIVATE MEMBER VARIABLES
////////////////////////////////////////////////////////////////////////////////

	std::vector< core_api::auto_generated_api::chemistry::atoms::AtomInstance_APICWP > atoms_;

}; // class AtomSelection

} // namespace atom_selectors
} // namespace selectors
} // namespace base_classes
} // namespace core_api
} // namespace masala

#endif // Masala_src_core_api_base_classes_selectors_AtomSelection_hh