/*
    Masala
    Copyright (C) 2022 Vikram K. Mulligan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/// @file src/core/selection/atom_selection/AtomSelection.fwd.hh
/// @brief A base class for AtomSelections.
/// @details AtomSelections are generated by AtomSelectors, and provide a list of a
/// subset of atoms to select.  They are dependent on the current Pose.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).

// Unit header:
#include <core/selection/atom_selection/AtomSelection.hh>

// Core headers:
#include <core/chemistry/atoms/AtomInstanceConstIterator.hh>
#include <core/chemistry/atoms/AtomInstance.hh>

// Base headers:
#include <base/utility/container/container_util.tmpl.hh>
#include <base/api/MasalaObjectAPIDefinition.hh>
#include <base/api/constructor/MasalaObjectAPIConstructorDefinition_OneInput.tmpl.hh>
#include <base/api/constructor/MasalaObjectAPIConstructorDefinition_ZeroInput.tmpl.hh>
#include <base/api/getter/MasalaObjectAPIGetterDefinition_ZeroInput.tmpl.hh>
#include <base/api/setter/MasalaObjectAPISetterDefinition_OneInput.tmpl.hh>

// STL headers:
#include <string>

namespace masala {
namespace core {
namespace selection {
namespace atom_selection {

////////////////////////////////////////////////////////////////////////////////
// CONSTRUCTION, DESTRUCTION, AND ASSIGNMENT
////////////////////////////////////////////////////////////////////////////////

/// @brief Copy constructor.
AtomSelection::AtomSelection(
	AtomSelection const & src
) :
	atoms_( src.atoms_ )
{}

/// @brief Assignment operator.
AtomSelection &
AtomSelection::operator=(
	AtomSelection const & src
) {
	atoms_ = src.atoms_;
	return *this;
}

/// @brief Create a copy of this object.
AtomSelectionSP
AtomSelection::clone() const {
	return masala::make_shared< AtomSelection >( *this );
}

/// @brief Create a copy of this object that is independent of the original.
AtomSelectionSP
AtomSelection::deep_clone() const {
	return masala::make_shared< AtomSelection >( *this );
}

////////////////////////////////////////////////////////////////////////////////
// PUBLIC MEMBER FUNCTIONS
////////////////////////////////////////////////////////////////////////////////

/// @brief Get the name of this class ("AtomSelection").
std::string
AtomSelection::class_name() const {
	return "AtomSelection";
}

/// @brief Get the namespace of this class ("masala::core::selection::atom_selection").
std::string
AtomSelection::class_namespace() const {
	return "masala::core::selection::atom_selection";
}

/// @brief Get the API definition for this object.
base::api::MasalaObjectAPIDefinitionCWP
AtomSelection::get_api_definition() {
    using namespace base::api;
    using namespace base::api::constructor;
    using namespace base::api::getter;
    using namespace base::api::setter;

    std::lock_guard< std::mutex > lock( whole_object_mutex_ );

	if( api_definition_ == nullptr ) {

        MasalaObjectAPIDefinitionSP api_def(
            masala::make_shared< MasalaObjectAPIDefinition >(
                *this,
                "A container for atoms and chemical bonds, and for data representations "
                "that allow efficient geometric manipulations.",
                false
            )
        );

        api_def->add_constructor(
            masala::make_shared< MasalaObjectAPIConstructorDefinition_ZeroInput< AtomSelection > >(
                class_name(), "Constructor that makes an empty AtomSelection."
            )
        );

        api_def->add_constructor(
            masala::make_shared< MasalaObjectAPIConstructorDefinition_OneInput< AtomSelection, AtomSelection const & > >(
                class_name(), "AtomSelection object copy constructor.",
                "src", "The input AtomSelection object to copy."
            )
        );

        api_def->add_getter(
            masala::make_shared< MasalaObjectAPIGetterDefinition_ZeroInput < core::Size > >(
                "num_selected_atoms", "Gets the total number of atoms that are in the selection.",
                "num_selected_atoms", "The number of atoms in the selection.",
                false, false,
                std::bind( &AtomSelection::num_selected_atoms, this )
            )
        );
        api_def->add_getter(
            masala::make_shared< MasalaObjectAPIGetterDefinition_ZeroInput < masala::core::chemistry::atoms::AtomInstanceConstIterator > >(
                "atoms_begin", "Get a const iterator over atoms, initialized to first atom.",
                "atoms_begin", "Iterator pointing to the first atom in the set stored in the selection.",
                false, false,
                std::bind( &AtomSelection::atoms_begin, this )
            )
        );
        api_def->add_getter(
            masala::make_shared< MasalaObjectAPIGetterDefinition_ZeroInput < masala::core::chemistry::atoms::AtomInstanceConstIterator > >(
                "atoms_end", "Get a const iterator over atoms, initialized to one past the last atom.",
                "atoms_end", "Iterator pointing one past the last atom in the set stored in the selection.",
                false, false,
                std::bind( &AtomSelection::atoms_end, this )
            )
        );

        api_def->add_setter(
            masala::make_shared< MasalaObjectAPISetterDefinition_OneInput < masala::core::chemistry::atoms::AtomInstanceCSP > >(
                "add_atom", "Add an atom to this selection.",
                "atom_in", "The atom to add to the selection.",
                false, false,
                std::bind( &AtomSelection::add_atom, this, std::placeholders::_1 )
            )
        );

        api_definition_ = api_def; // Nonconst to const.
    }
    return api_definition_;

}

/// @brief Get the category or categories for this plugin class.
/// @returns { { "Selection", "AtomSelection" } }
/// @note Categories are hierarchical (e.g. Selector->AtomSelector->AnnotatedRegionSelector,
/// stored as { {"Selector", "AtomSelector", "AnnotatedRegionSelector"} }). A plugin can be
/// in more than one hierarchical category (in which case there would be more than one
/// entry in the outer vector), but must be in at least one.  The first one is used as
/// the primary key.
std::vector< std::vector< std::string > >
AtomSelection::get_categories() const {
	return std::vector< std::vector< std::string > > {
		{ "Selection", "AtomSelection" }
	};
}

/// @brief Get the keywords for this plugin class.
/// @returns { "masala", "core", "selection", "atom_selection" }
std::vector< std::string >
AtomSelection::get_keywords() const {
	return std::vector< std::string > {
		"masala",
		"core",
		"selection",
		"atom_selection"
	};
}

/// @brief Add an atom to the selection
void
AtomSelection::add_atom(
	core::chemistry::atoms::AtomInstanceCSP const & atom_in
) {
	std::lock_guard< std::mutex > lock( whole_object_mutex_ );

	// Do not add if already in vector.
	if( !masala::base::utility::container::has_value( atoms_, atom_in ) ) {
		atoms_.insert( atom_in );
	}
}

/// @brief Get the number of selected atoms in this selection.
masala::core::Size
AtomSelection::num_selected_atoms() const {
	std::lock_guard< std::mutex > lock( whole_object_mutex_ );
	return atoms_.size();
}

/// @brief An iterator pointing to the first atom.
masala::core::chemistry::atoms::AtomInstanceConstIterator
AtomSelection::atoms_begin() const {
	return masala::core::chemistry::atoms::AtomInstanceConstIterator( atoms_.cbegin() );
}

/// @brief An iterator pointing to the element past the last atom.
masala::core::chemistry::atoms::AtomInstanceConstIterator
AtomSelection::atoms_end() const {
	return masala::core::chemistry::atoms::AtomInstanceConstIterator( atoms_.cend() );
}

} // namespace atom_selection
} // namespace selection
} // namespace core
} // namespace masala
