/*
    Masala
    Copyright (C) 2025 Vikram K. Mulligan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/// @file src/core/selection/atom_selection/AtomSelection.fwd.hh
/// @brief Forward declarations for a base class for AtomSelections.
/// @details AtomSelections are generated by AtomSelectors, and provide a list of a
/// subset of atoms to select.  They are dependent on the current MolecularSystem.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).

#ifndef Masala_src_core_selection_atom_selection_AtomSelection_fwd_hh
#define Masala_src_core_selection_atom_selection_AtomSelection_fwd_hh

#include <base/managers/memory/util.hh> // For MASALA_SHARED_POINTER

namespace masala {
namespace core {
namespace selection {
namespace atom_selection {

	class AtomSelection;

	/// @brief We will use the convention that an class name followed by SP
	/// represents a MASALA_SHARED_POINTER for objects of that class.
	using AtomSelectionSP = MASALA_SHARED_POINTER< AtomSelection >;

	/// @brief We will use the convention that an class name followed by CSP
	/// represents a MASALA_SHARED_POINTER for const objects of that class.
	using AtomSelectionCSP = MASALA_SHARED_POINTER< AtomSelection const >;

	/// @brief We will use the convention that an class name followed by WP
	/// represents a MASALA_WEAK_POINTER for objects of that class.
	using AtomSelectionWP = MASALA_WEAK_POINTER< AtomSelection >;

	/// @brief We will use the convention that an class name followed by CWP
	/// represents a MASALA_WEAK_POINTER for const objects of that class.
	using AtomSelectionCWP = MASALA_WEAK_POINTER< AtomSelection const >;

} // namespace atom_selection
} // namespace selection
} // namespace core
} // namespace masala

#endif //Masala_src_core_selection_atom_selection_AtomSelection_fwd_hh