/*
    Masala
    Copyright (C) 2022 Vikram K. Mulligan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/// @file src/core/selection/Selection.fwd.hh
/// @brief Forward declarations for a pure virtual base class for Selections.
/// @details Selections are generated by Selectors, and provide a list of a
/// subset of something (atoms, residues, etc.) to select.  They are dependent
/// on the current MolecularSystem.
/// @note Since this class does not implement class_name() or class_namespace()
/// functions required by the MasalaObject base class, it remains pure virtual.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).

#ifndef Masala_src_core_selecion_Selection_fwd_hh
#define Masala_src_core_selecion_Selection_fwd_hh

#include <base/managers/memory/util.hh> // For MASALA_SHARED_POINTER

namespace masala {
namespace core {
namespace selection {

	class Selection;

	/// @brief We will use the convention that an class name followed by SP
	/// represents a MASALA_SHARED_POINTER for objects of that class.
	using SelectionSP = MASALA_SHARED_POINTER< Selection >;

	/// @brief We will use the convention that an class name followed by CSP
	/// represents a MASALA_SHARED_POINTER for const objects of that class.
	using SelectionCSP = MASALA_SHARED_POINTER< Selection const >;

	/// @brief We will use the convention that an class name followed by WP
	/// represents a MASALA_WEAK_POINTER for objects of that class.
	using SelectionWP = MASALA_WEAK_POINTER< Selection >;

	/// @brief We will use the convention that an class name followed by CWP
	/// represents a MASALA_WEAK_POINTER for const objects of that class.
	using SelectionCWP = MASALA_WEAK_POINTER< Selection const >;

} // namespace selection
} // namespace core
} // namespace masala

#endif //Masala_src_core_selecion_Selection_fwd_hh