/*
    Masala
    Copyright (C) 2025 Vikram K. Mulligan

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/// @file src/core_api/base_classes/selectors/atom_selectors/annotated_region_selectors/AnnotatedRegionSelection.fwd.hh
/// @brief Header for a pure virtual base class for AnnotatedRegionSelections.
/// @details AnnotatedRegionSelections are generated by AnnotatedRegionSelectors, and provide a list of a
/// subset of atoms to select based on annotated regions.  They are dependent on the current MolecularSystem.
/// @note Since this class does not implement class_name() or class_namespace()
/// functions required by the MasalaObject base class, it remains pure virtual.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).

#ifndef Masala_src_core_api_base_classes_selectors_atom_selectors_annotated_region_selectors_AnnotatedRegionSelection_hh
#define Masala_src_core_api_base_classes_selectors_atom_selectors_annotated_region_selectors_AnnotatedRegionSelection_hh

// Parent class:
#include <core/selection/atom_selection/AtomSelection.hh>

// Forward declarations:
#include <core_api/base_classes/selectors/atom_selectors/annotated_region_selectors/AnnotatedRegionSelection.fwd.hh>

// Base headers:
#include <base/MasalaObject.hh>

namespace masala {
namespace core_api {
namespace base_classes {
namespace selectors {
namespace atom_selectors {
namespace annotated_region_selectors {

/// @brief A pure virtual base class for AnnotatedRegionSelections.
/// @details AnnotatedRegionSelections are generated by AnnotatedRegionSelectors, and provide a list of a
/// subset of atoms to select based on annotated regions.  They are dependent on the current MolecularSystem.
/// @note Since this class does not implement class_name() or class_namespace()
/// functions required by the MasalaObject base class, it remains pure virtual.
/// @author Vikram K. Mulligan (vmulligan@flatironinstitute.org).
class AnnotatedRegionSelection : public masala::core::selection::atom_selection::AtomSelection {

public:

	/// @brief Default constructor.
	AnnotatedRegionSelection() = default;

	/// @brief Copy constructor.
	AnnotatedRegionSelection( AnnotatedRegionSelection const & ) = default;

	/// @brief Destructor.
	~AnnotatedRegionSelection() override = default;

}; // class AnnotatedRegionSelection

} // namespace annotated_region_selectors
} // namespace atom_selectors
} // namespace selectors
} // namespace base_classes
} // namespace core_api
} // namespace masala

#endif // Masala_src_core_api_base_classes_selectors_atom_selectors_annotated_region_selectors_AnnotatedRegionSelection_hh